### PR TITLE
json-patch demo refactoring

### PR DESCRIPTION
**Pull request by cvasilak**
done for [https://issues.jboss.org/browse/AGIOS-359](AGIOS-359)

@corinnekrych @danbev mind to have a look

### CODE REVIEW

**Comment by danbev** [comment]
Will take a :eyes: later today

**Comment by danbev** [comment]
@cvasilak Works as advertised. I'm using the sync-server from https://github.com/aerogear/aerogear-sync-server/pull/27. Will take a closer look at the code now.

**Comment by danbev** [comment]
:+1: With or without the above suggestions.

**Comment by cvasilak** [comment]
thank you @danbev have updated with your suggestions

**Comment by matzew** [comment]
:+1:

**Comment by corinnekrych** [comment]
:+1:

**Pull request merged**
