### PR TITLE
remove Podfile.lock

### PR DESCRIPTION
**Pull request by corinnekrych**
@danbev @cvasilak as discussed since the version information is in Podfile, let's remove unnecessary lock file

### CODE REVIEW

**Comment by matzew** [comment]
+1

On Thu, Jan 29, 2015 at 9:29 AM, Corinne Krych <notifications@github.com>
wrote:

> @danbev <https://github.com/danbev> @cvasilak
> <https://github.com/cvasilak> as discussed since the version information
> is in Podfile, let's remove unnecessary lock file
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/aerogear/aerogear-ios-sync-demo/pull/2
> Commit Summary
>
>    - remove Podfile.lock
>
> File Changes
>
>    - *D* Podfile.lock
>    <https://github.com/aerogear/aerogear-ios-sync-demo/pull/2/files#diff-0>
>    (22)
>
> Patch Links:
>
>    - https://github.com/aerogear/aerogear-ios-sync-demo/pull/2.patch
>    - https://github.com/aerogear/aerogear-ios-sync-demo/pull/2.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-ios-sync-demo/pull/2>.
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by danielpassos** [comment]
Hrm. If we don't need that, maybe add in .gitignore? Wdyt?

**Comment by corinnekrych** [comment]
@passos Good point! let me add it

**Comment by cvasilak** [comment]
:+1:

**Pull request merged**
